### ISSUE TITLE
question about bitmatch

### ISSUE THREAD

**Issue by olegkhr** [ARM-software/CMSIS-DSP#115]
1. Does Helium and non-Helium versions of quantized transform functions produce exactly same result?
2. Does Python wrapper produce bitmatching result for quantized transform functions?

**Comment by christophe0606** [comment]
@olegkhr There are some small differences in some cases because otherwise being fully identical was preventing from having good performance increase.
The Python wrapper is using the pure C version and should be identical to the other DSP versions (M4 ..).

It is only the vectorized versions (Neon, Helium) that may be a bit different.

Another reason is that often the algorithm is different : a vectorized biquad for instance is not at all the same algorithm (so different behavior for rounding etc ...)

We use a SNR measurement (not only) and check that all versions on all cores are below the SNR. So even if they are not identical, from DSP point of view it should not be a problem.

(SNR threshold is defined on an algorithm basis in the tests. It is not global).
