### ISSUE TITLE
Build is not working on GCC

### ISSUE THREAD

**Issue by elagil** [ARM-software/CMSIS-DSP#189]
Hello!

I noticed a recent change in https://github.com/ARM-software/CMSIS-DSP/blob/main/Include/arm_math_types.h#L67 .
The addition of this line practically disables the inclusion of `cmsis_gcc.h` so that the compile specific defines are now unknown - e.g. `__STATIC_INLINE`. This breaks the build for me.

Is that intentional?
Thank you!

**Comment by christophe0606** [comment]
@elagil Hello. Thank you for the report. I'll change the name because it conflicts with some version of CMSIS Core.
This flag is used to disable some vectorial versions when compiled with gcc (Helium target) because of some code generation issues with gcc in some cases. But it should have only a very localised impact.

**Comment by christophe0606** [comment]
@elagil I have pushed an attempted fix. Tell me if it solves the issue.

Also, how are you building ? I am building with gcc but did not see the issue so I assume it is related to CMSIS Core. I am testing with ARM::CMSIS@6.0.0 and the problem does not occur.

But anyway, using `__CMSIS_GCC_H` was wrong so now it should work with CMSIS 5 and 6.

**Comment by elagil** [comment]
@christophe0606 Thanks for the quick answer! This builds fine now.

I am still on CMSIS 5.
