### ISSUE TITLE
Integer size type overflow warnings in 16-bit fast atan

### ISSUE THREAD

**Issue by petertorelli** [ARM-software/CMSIS-DSP#74]
When compiling with gcc 11.3.0 on Cygwin (!), I encounter overflow warnings, such as this one:

```
../CMSIS-DSP/Source/FastMathFunctions/arm_atan2_q15.c:48:2: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘65535’ to ‘-1’ [-Woverflow]
   48 | ,0xffff
      |  ^~~~~~
../CMSIS-DSP/Source/FastMathFunctions/arm_atan2_q15.c:49:2: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘54631’ to ‘-10905’ [-Woverflow]
   49 | ,0xd567
      |  ^~~~~~
../CMSIS-DSP/Source/FastMathFunctions/arm_atan2_q15.c:50:2: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘65392’ to ‘-144’ [-Woverflow]
   50 | ,0xff70
      |  ^~~~~~
../CMSIS-DSP/Source/FastMathFunctions/arm_atan2_q15.c:52:2: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘64856’ to ‘-680’ [-Woverflow]
   52 | ,0xfd58
      |  ^~~~~~
../CMSIS-DSP/Source/FastMathFunctions/arm_atan2_q15.c:53:2: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘59817’ to ‘-5719’ [-Woverflow]
   53 | ,0xe9a9
      |  ^~~~~~
../CMSIS-DSP/Source/FastMathFunctions/arm_atan2_q15.c:55:2: warning: overflow in conversion from ‘int’ to ‘short int’ changes value from ‘64475’ to ‘-1061’ [-Woverflow]
   55 | ,0xfbdb
      |  ^~~~~~
```

Is this a legit problem or an overzealous compiler warning (or Arm passive-aggressively telling me to stop using x86 :smile:)?

**Comment by christophe0606** [comment]
@petertorelli I think for some reason gcc is considering those values as unsigned and so obviously they can't be represented as signed 16 bit values.

But they should not be considered as unsigned. 

I don't think the generated table is wrong and that gcc is doing any kind of conversion. Probably just a warning to tell the user that the value will be signed at the end and perhaps not what the user was expecting.

I don't remember if MSVC on Windows is also generating those warnings.
But it looks like the gcc for arm has a different behavior here.

What compilation flags are you using ?

**Comment by christophe0606** [comment]
I generally use `-Wdouble-promotion -std=c11 -Ofast -ffast-math -DNDEBUG -Wall -Wextra`

`-pedantic` may be the explanation for the warning ...

**Comment by ehntoo** [comment]
I just encountered this warning. `-pedantic` is the flag that causes GCC to warn about the condition, reproduced in a minimal compiler explorer example here: https://gcc.godbolt.org/z/eYvbWhdzz. Clang also produces the same warning when given the `-Wsign-conversion` or `-Weverything` flags. The sign conversion here appears to be desired and the result of the code should be correct, but the warning is not technically spurious.

From the c11 draft standard section 6.4.4.1,
> The type of an integer constant is the first of the corresponding list in which its value can be represented
<img width="480" alt="Screen Shot 2022-12-13 at 11 38 11 AM" src="https://user-images.githubusercontent.com/110989/207391432-d3f9a90f-f18c-4559-b2b8-4f40eba78fcc.png">

The constant values being warned about fit into the `int` (either 32 or 64-bit signed on the machine from the initial post) type, so the compiler considers them `int` values as there is no suffix. The value of `0xffff` interpreted as an 32- or 64-bit sized _signed_ value is `+65535`, but when implicitly cast into the 16-bit signed `q15_t` type, the value overflows to `-1`. That is, the warnings are correct, even if the code has the desired behavior.

This warning can be handled either by expressing the constants in `atan2_coefs_q15` as negative decimal values so that no sign conversion takes place, or adding an explicit cast to `q15_t` to the hexadecimal constants.

**Comment by petertorelli** [comment]
@ehntoo Thanks for the citation and explanation!

@christophe0606 It isn't readily obvious to the non-DSP layperson from looking at the code that there is no sign bug (esp. since the only use of this table casts the values back to 32-bit just a dozen lines later in the function `arm_atan_limited_q15`). But it literally falls under "pedantic". I'll close. Thanks!

**Comment by ehntoo** [comment]
@petertorelli I think it may be valuable to fix this warning even if it's `-pedantic`, _especially_ since the values are later cast to 32-bit signed values, as the code is then relying on sign extension happening for the 16-bit constants.

**Comment by petertorelli** [comment]
@ehntoo I don't know how to regress edits to CMSIS-DSP but I created a PR; also not sure what kind of magic is happening in that code, and if the hex values are relevant, so I left them in the comments.
