### ISSUE TITLE
arm_mat_inverse_f32 error

### ISSUE THREAD

**Issue by gerrlang** [ARM-software/CMSIS-DSP#78]
Hi,

I just started using CMSIS and I'm having trouble with the matrix inversion.
Using a STM32F446RE Nucleo board.
![error](https://user-images.githubusercontent.com/121313350/209392668-0feff83b-1c7a-4dd9-acb2-e647f1cf7e1c.JPG)

This is mostly from the example code, however i'm trying to calculate the inverse of A.
Getting a singularity status and ATMAI containing 0,1,-1
Matlab returns a different inverse.
![comp](https://user-images.githubusercontent.com/121313350/209393021-d61c3346-beef-4375-925c-f74a2d911781.JPG)

Can someone help me figure out if this is an issue with the function or the user?
arm_math.h shows version V1.4.5 b  (seems to be the one that STM32Cube includes when adding CMSIS DSP)

Any help is appreciated

[main.txt](https://github.com/ARM-software/CMSIS-DSP/files/10296885/main.txt)

**Comment by christophe0606** [comment]
@gerrlang Sorry for late answer, I was on vacations.
V1.4.5 is a very old version.

I remember than in older versions the matrix inversion was not using any pivoting strategy and thus was numerically more instable.

I have tested with latest version and I am getting the correct result.

Your version of the library is returning the error code ARM_MATH_SINGULAR meaning it was not able to invert the matrix and probably got some 0 on the diagonal during the process. So the output matrix is not containing any correct values and should not be used.

Note that, if possible, it is always better to use different algorithm than matrix inversion because matrix inversion is not behaving very well numerically in general.

The matrix you are trying to invert is not well conditioned (big ratio between biggest and smallest singular value) so the inversion algorithms may not behave well.
